### ISSUE TITLE
Calling another method in the same class from equals results in a StackOverflowError

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#108]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 16, 2009 18:40:35_

E.g. 
public class ClassA 
{
     
   @Override
       public int hashCode()
   {
       return getId();
   }

   public int getId()
   {
       return 3;
   }
}

_Original issue: http://code.google.com/p/powermock/issues/detail?id=88_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 19, 2009 12:43:39_

Fixed in trunk for version 1.2

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 22, 2009 05:42:50_

Issue 89 has been merged into this issue.

**Comment by johanhaleby** [comment]
_From [marcel.f...@googlemail.com](https://code.google.com/u/109375337160289163578/) on April 15, 2009 05:49:54_

There seems to be a similar problem for classes implementing equals() as a final
method which calls another method of that class.
The attached example provokes a StackOverflowError when executed.

StackTrace:
java.lang.StackOverflowError
	at java.lang.reflect.Field.<init>(Field.java:103)
	at java.lang.reflect.Field.copy(Field.java:126)
	at java.lang.reflect.ReflectAccess.copyField(ReflectAccess.java:122)
	at sun.reflect.ReflectionFactory.copyField(ReflectionFactory.java:289)
	at java.lang.Class.copyFields(Class.java:2711)
	at java.lang.Class.getDeclaredFields(Class.java:1715)
	at org.powermock.reflect.internal.WhiteboxImpl.getField(WhiteboxImpl.java:188)
	at org.powermock.core.MockGateway.fieldCall(MockGateway.java:117)
	at powermocktest.ClassToMock.equals(PowerMockEqualsTest.java)
	at org.easymock.internal.ExpectedInvocation.matches(ExpectedInvocation.java:77)
	at org.easymock.internal.UnorderedBehavior.addActual(UnorderedBehavior.java:38)
	at org.easymock.internal.MocksBehavior.addActual(MocksBehavior.java:74)
	at org.easymock.internal.ReplayState.invokeInner(ReplayState.java:37)
	at org.easymock.internal.ReplayState.invoke(ReplayState.java:33)
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:27)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:61)
	at
org.powermock.api.easymock.internal.signedsupport.SignedSupportingClassProxyFactory$1.intercept(SignedSupportingClassProxyFactory.java:125)
	at powermocktest.ClassToMock$$EnhancerByCGLIB$$8fa55cb1.equals(<generated>)
	at powermocktest.ClassToMock.equals(PowerMockEqualsTest.java:45)
	at org.easymock.internal.ExpectedInvocation.matches(ExpectedInvocation.java:77)
	at org.easymock.internal.UnorderedBehavior.addActual(UnorderedBehavior.java:38)
	at org.easymock.internal.MocksBehavior.addActual(MocksBehavior.java:74)
	at org.easymock.internal.ReplayState.invokeInner(ReplayState.java:37)
	at org.easymock.internal.ReplayState.invoke(ReplayState.java:33)
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:27)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:61)
	at
org.powermock.api.easymock.internal.signedsupport.SignedSupportingClassProxyFactory$1.intercept(SignedSupportingClassProxyFactory.java:125)
...

**Attachment:** [PowerMockEqualsTest.java](http://code.google.com/p/powermock/issues/detail?id=88#hc3)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 15, 2009 06:51:36_

I'll look into it asap, thanks!

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 16, 2009 04:45:58_

I've verified the problem and it's a bug. Thanks for finding this! We'll do our best
to solve it.

**Comment by johanhaleby** [comment]
_From [jan.kron...@gmail.com](https://code.google.com/u/111289048178412145391/) on April 27, 2009 09:21:28_

**Summary:** Calling another method in the same class from equals results in a StackOverflowError  
  **Status:** Accepted

**Comment by johanhaleby** [comment]
_From [jan.kron...@gmail.com](https://code.google.com/u/111289048178412145391/) on April 27, 2009 09:56:49_

**Labels:** Milestone-Release1.3

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 19, 2009 12:41:37_

**Labels:** -Milestone-Release1.3 Milestone-Release1.4

**Comment by johanhaleby** [comment]
_From [felip...@gmail.com](https://code.google.com/u/101306523760723956770/) on May 05, 2010 10:52:31_

I'm facing a similar issue when trying to mock a final class. My test code is
something like this:

  Project project = PowerMock.createMock(Project.class); EasyMock .expect(project.getURL()).andReturn(url);
  PowerMock.replay(project);

Then the replay method throws a StackOverflowError:

java.lang.StackOverflowError
	at org.powermock.reflect.internal.WhiteboxImpl$2.run(WhiteboxImpl.java:1287)
	at org.powermock.reflect.internal.WhiteboxImpl$2.run(WhiteboxImpl.java:1284)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.powermock.reflect.internal.WhiteboxImpl.getAllMethods(WhiteboxImpl.java:1284)
	at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1526)
	at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1564)
	at
org.powermock.reflect.internal.WhiteboxImpl.getBestMethodCandidate(WhiteboxImpl.java:836)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:82)
	at org.powermock.core.MockGateway.methodCall(MockGateway.java:148)
	at ProjectSuperClass.identical(ProjectSuperClass.java)
	at Project.equals(Project.java:789)
	at org.easymock.internal.Invocation.equals(Invocation.java:95)


The problem lies on Easymock's relying on the equals() method defined in the class
being mocked:

    public boolean equals(Object o) {
        if (o == null || !o.getClass().equals(this.getClass()))
            return false;

        Invocation other = (Invocation) o;

        return this.mock.equals(other.mock) && this.method.equals(other.method)
                && this.equalArguments(other.arguments);
    }

Which in the case of Project is something like:

  public final boolean equals(Object o)
  {
    if ( o == null || o.getClass() != getClass() ) {
      return false;
    } else {
      return identical(o);
    }
  }

Because o.getClass() != getClass() fails (as o's class is the bytecode-enhanced
class), it calls method identical(), which recursively calls equals(). I think the
solution would be to not rely on equals() in this case, but in other mechanism like
System.identityHashCode:

        return System.identityHashcode(this.mock) ==
System.identityHashcode(other.mock)&& ...


-- Felipe

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 06, 2010 23:09:17_

Hi, 

We're aware of this. I've actually made fixes in trunk which solves the issue(s) with 
Mockito making it possible to mock/suppress/stub final toString, equals and hashcode 
methods. However for EasyMock you'd have to modify the internals of EasyMock for this 
to work (just as you point out). Perhaps you could bring this up on the EasyMock mailinglist? Mockito doesn't have this issue so there must another way for them to do 
it.

/Johan

**Comment by johanhaleby** [comment]
_From [felip...@gmail.com](https://code.google.com/u/101306523760723956770/) on May 07, 2010 09:36:22_

Changing Easymock's Invocation to use System.identityHashMap() fixes it. I will try
to write a simpler test case (that does not rely on PowerMock) to reproduce the
issue, then submit a patch to Easymock.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 07, 2010 10:43:32_

Excellent!

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 22, 2010 02:16:22_

**Labels:** -Milestone-Release1.4 Milestone-Release1.5

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 08, 2010 02:02:51_

Changing to a lower priority since this will hopefully be solved by the EasyMock team.

**Labels:** -Milestone-Release1.5 Milestone-Release2.0

**Comment by johanhaleby** [comment]
_From [gfo...@gmail.com](https://code.google.com/u/101100060564095379550/) on August 31, 2010 14:15:23_

We have a similar problem with StackOverflowError, using either PowerMock version 1.3.8 with mockito 1.8.4 or PowerMock version 1.4.5 with mockito 1.8.5.

Relevant lines from the stack trace:
java.lang.StackOverflowError
        at java.security.AccessController.doPrivileged(Native Method)
        at org.powermock.reflect.internal.WhiteboxImpl.getAllMethods(WhiteboxImpl.java:1626)
        at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1909)
        at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1952)
        at org.powermock.reflect.internal.WhiteboxImpl.getBestMethodCandidate(WhiteboxImpl.java:1056)
        at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:89)
        at org.powermock.core.MockGateway.methodCall(MockGateway.java:168)
        at com.google.gwt.core.client.JavaScriptObject.equals(JavaScriptObject.java)
        at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:57)
        at org.mockito.internal.stubbing.InvocationContainerImpl.findAnswerFor(InvocationContainerImpl.java:72)
        at org.mockito.internal.MockHandler.handle(MockHandler.java:93)
        at org.powermock.api.mockito.internal.invocationcontrol.MockitoMethodInvocationControl.performIntercept(MockitoMethodInvocationControl.java:267)
        at org.powermock.api.mockito.internal.invocationcontrol.MockitoMethodInvocationControl.invoke(MockitoMethodInvocationControl.java:169)
        at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:105)
        at org.powermock.core.MockGateway.methodCall(MockGateway.java:168)
        at com.google.gwt.core.client.JavaScriptObject.equals(JavaScriptObject.java)
...

We can also post source code if needed or try to minimize to a suitable test case.

As I read this bug, and according to comment 10,  it should have been fixed for mockito with the following commit: https://code.google.com/p/powermock/source/detail?r=1294 which is also mentioned in the change log for PowerMock 1.3.8.

So is this fixed for any combination of PowerMock / Mockito? Has it been released?

If you need more info feel free to ask!

Thanks,
-fotos

**Comment by johanhaleby** [comment]
_From [teevee...@hotmail.co.uk](https://code.google.com/u/109045894023837764685/) on October 19, 2010 08:31:55_

I've also been getting StackOverflowErrors when trying to mock a class with a final method. The class has a superclass that overrides equals(). If I remove the equals() implementation then the error does not occur and the test completes normally. I am using powermock 1.4.6 (also tried 1.4.5) with JUnit 4.8.1, downloaded with maven:

   \<dependency>
      \<groupId>org.powermock</groupId>
      \<artifactId>powermock-module-junit4</artifactId>
      \<version>1.4.6</version>
      \<scope>test</scope>
   \</dependency>
   \<dependency>
      \<groupId>org.powermock</groupId>
      \<artifactId>powermock-api-mockito</artifactId>
      \<version>1.4.6</version>
      \<scope>test</scope>
   \</dependency>

**Comment by johanhaleby** [comment]
_From [linh.dan...@gmail.com](https://code.google.com/u/111171308910314323569/) on January 24, 2011 01:13:17_

I have the same issue. Has the fix been released?

**Comment by johanhaleby** [comment]
_From [forthw...@gmail.com](https://code.google.com/u/110542453770257841986/) on August 10, 2011 13:31:33_

I am having the same issue as well.  I am using PowerMock  1.4.9 with Mockito 1.8.5.  Following is the stack trace:

java.lang.StackOverflowError
	at java.lang.ref.Reference.get(Reference.java:160)
	at java.lang.ref.SoftReference.get(SoftReference.java:93)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2421)
	at java.lang.Class.getDeclaredMethods(Class.java:1791)
	at org.powermock.reflect.internal.WhiteboxImpl$3.run(WhiteboxImpl.java:1608)
	at org.powermock.reflect.internal.WhiteboxImpl$3.run(WhiteboxImpl.java:1605)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.powermock.reflect.internal.WhiteboxImpl.getAllMethods(WhiteboxImpl.java:1605)
	at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1888)
	at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1931)
	at org.powermock.reflect.internal.WhiteboxImpl.getBestMethodCandidate(WhiteboxImpl.java:1025)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:89)
	at org.powermock.core.MockGateway.methodCall(MockGateway.java:168)
	at net.sf.ehcache.Element.equals(Element.java)
	at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:57)
	at org.mockito.internal.stubbing.InvocationContainerImpl.findAnswerFor(InvocationContainerImpl.java:72)
	at org.mockito.internal.MockHandler.handle(MockHandler.java:93)
	at org.powermock.api.mockito.internal.invocationcontrol.MockitoMethodInvocationControl.performIntercept(MockitoMethodInvocationControl.java:291)
	at org.powermock.api.mockito.internal.invocationcontrol.MockitoMethodInvocationControl.invoke(MockitoMethodInvocationControl.java:193)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:105)
	at org.powermock.core.MockGateway.methodCall(MockGateway.java:168)
	...
	at net.sf.ehcache.Element.equals(Element.java)
	at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:57)
	at org.mockito.internal.stubbing.InvocationContainerImpl.findAnswerFor(InvocationContainerImpl.java:72)

**Comment by johanhaleby** [comment]
_From [michael....@gmail.com](https://code.google.com/u/104543144845657664420/) on September 08, 2011 02:04:26_

I have the same issue. Has the fix been released? Where can I get it?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 08, 2011 03:01:11_

Unfortunately not. I'd really appreciate some help with this.

**Comment by johanhaleby** [comment]
_From [michael....@gmail.com](https://code.google.com/u/104543144845657664420/) on September 08, 2011 06:21:17_

ok it works, if you remove the "final" from the "equals"-method

**Comment by johanhaleby** [comment]
_From [michael....@gmail.com](https://code.google.com/u/104543144845657664420/) on September 08, 2011 06:21:46_

But, why?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 08, 2011 07:02:29_

When I wrote this, only God and I understood what I was doing. Now, God only knows.

**Comment by johanhaleby** [comment]
_From [gloeckne...@gmail.com](https://code.google.com/u/116867748864641808723/) on January 25, 2012 03:51:03_

Hi guys,

Still reproducible with Mockito 1.9.0 and Powermock 1.4.11. Actually, it's reproducible with any final equals().

Regards,
Daniel

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 25, 2012 04:11:22_

There has been no work on this from my side. Please help out.

**Comment by johanhaleby** [comment]
_From [kals...@gmail.com](https://code.google.com/u/108947505188606736483/) on April 02, 2012 08:53:11_

I am having this issue as well - any plans to solve it in near future?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 02, 2012 10:38:41_

I would really appreciate some help with this issue. Provide a patch and I'll include it in the next release.

**Comment by johanhaleby** [comment]
_From [karlek...@gmail.com](https://code.google.com/u/109011204024968417834/) on May 15, 2012 04:48:31_

Hi all,

I've attached some simple code to parse a .class file and generate a new .class file with all final Opcodes removed.

I'm not really familiar with how ClassLoaders work but I guess this could be adapted to modify the target classes at runtime removing final from only the equals method.

Not sure if this is helpful or not.  For now I'm just parsing my 3rd party libraries class files with it so that I can run the tests.

Karle

**Attachment:** [BytecodeModifier.java](http://code.google.com/p/powermock/issues/detail?id=88#hc30)

**Comment by johanhaleby** [comment]
_From [karlek...@gmail.com](https://code.google.com/u/109011204024968417834/) on May 15, 2012 04:49:46_

Oops, chopped off imports from above:

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

Dependencies: asm-4.0.jar

**Comment by johanhaleby** [comment]
_From [mark.dav...@gmail.com](https://code.google.com/u/114492450221559828237/) on July 02, 2012 09:41:34_

Also seeing this issue: Mockito 1.8.5 & Powermocks 1.4.9.  I don't have control over the code with the offending final equals.. any suggestions on a workaround to mock it..?

**Comment by johanhaleby** [comment]
_From [peer.har...@gmail.com](https://code.google.com/u/106983985801872148399/) on April 10, 2014 09:24:56_

I think I might have found a fix for that. 

The idea is to add an identity check to org.mockito.internal.invocation.InvocationMatcher.matches(Invocation). The code here looks as follows:

  public boolean matches(Invocation actual) {
      return invocation.getMock().equals(actual.getMock()) && hasSameMethod(actual)
      && new ArgumentsComparator().argumentsMatch(this, actual);
  }

It seems to me that calling equals on invocation.getMock() ends up in the same method and thereby triggers the StackOverflow. My solution to that would be to make an identity comparision. When the identity is the same the objects must be equal too, at least for common java standards. When I change the matches-method to the following:

public boolean matches(Invocation actual) {
return (
invocation.getMock() == actual.getMock()
|| invocation.getMock().equals(actual.getMock())
) && hasSameMethod(actual) && new ArgumentsComparator().argumentsMatch(this, actual);
}

My test completes

I cannot really tell if this has any unwanted side-effects, but as I just wrote, according to java standards it should not.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 11, 2014 02:12:09_

Is this code change required inside Mockito? Is there anything we can do from the PowerMock side?

**Comment by johanhaleby** [comment]
_From [peer.har...@gmail.com](https://code.google.com/u/106983985801872148399/) on April 29, 2014 00:53:11_

Yes I think so. You could identify that problem in the MockGateway class and perform a workaround there. I attach an updated version with a fix. It uses Mockito's MethodGuru to identify the situation and then simply returns PROCEED which results in a call to the real method.
Since AFAIK it is not possible to Mock equals-Methods with mockito, that should be the desired behavior. But again I am not an expert on PowerMock's internal concepts...

**Attachment:** [FinalClass.java FinalClassTest.java MockGateway.java](http://code.google.com/p/powermock/issues/detail?id=88#hc35)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 04, 2014 11:07:38_

Could you please provide this patch as a pull request on github??

**Comment by johanhaleby** [comment]
_From [rsroman...@gmail.com](https://code.google.com/u/101982192061231037056/) on June 13, 2014 12:16:11_

I was able to work around this issue by setting:

MockGateway.MOCK_STANDARD_METHODS = false;

It makes MockGateway not mock toString, hashcode, and equals.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 10, 2014 11:34:50_

This should now have been fixed in master. Published a new snapshot, depend on version 1.5.6-SNAPSHOT to try it out after having added the following repo:

\<repositories>
        \<repository>
            \<id>sonatype</id>
            \<url> https://oss.sonatype.org/content/repositories/snapshots/</url> \<snapshots />
        \</repository>
\</repositories>

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 10, 2014 11:35:00_

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [siddhart...@gmail.com](https://code.google.com/u/115879996904320164008/) on September 22, 2014 21:00:53_

I could still see this issue. I can see that the status has been updated to Fixed. But can you please provide the Mockito and PowerMock versions post which we will not see this issue?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 22, 2014 22:14:13_

Try the latest version of PowerMock and Mockito

**Comment by KowKiller** [comment]
Hi,
It seems that I still get the StackOverflowError when mocking an object with a final equals/hashCode methods that call other methods of the same mocked object.

I am using the latest PowerMock version (1.6.3).

Here is the sample code. If I remove the final keyword from equals/hashCode, it works.

```java
public class ClassWithFinalEquals {
	
	public int methodToStub() {
		throw new UnsupportedOperationException();
	}
	
	@Override
	public final int hashCode() {
		return innerHashCode();
	}

	@Override
	public final boolean equals(Object obj) {
		return innerEquals(obj);
	}

	private int innerHashCode() {
		throw new UnsupportedOperationException();
	}
	
	private boolean innerEquals(Object obj) {
		throw new UnsupportedOperationException();
	}

}

@RunWith(PowerMockRunner.class)
@PrepareForTest({ClassWithFinalEquals.class})
public class FinalEqualsTest {
	
	@Test
	public void test() {
		ClassWithFinalEquals mockClassWithFinalEquals = PowerMockito.mock(ClassWithFinalEquals.class);
		
		PowerMockito.when(mockClassWithFinalEquals.methodToStub()).thenReturn(33);
		assertEquals(33, mockClassWithFinalEquals.methodToStub());
	}
	
}
```

Do you know any workaround for this?
