### ISSUE TITLE
Mockito 1.10.x ArgumentCaptor does not work with multi-argument constructor

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#541]
_From [jrh...@gmail.com](https://code.google.com/u/110694536384347452794/) on October 14, 2014 03:32:22_

With a project using Mockito 1.10.8, mock a multi-argument constructor using an ArgumentCaptor and then verify the captured value. I've recreated the problem using this simple project: https://github.com/jrh3k5/powermock-mockito-0.10.x-argument-captor I know that PowerMock 1.5.6 isn't validated/built against Mockito 1.10.8, but, given that I'm not likely the only one excited to not be on a version of Mockito that's over 2 years old, I thought this should be something on the radar for an eventual uplift to a newer version of Mockito.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=521_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 13, 2014 05:57:14_

I think this has been fixed in master. Please try to build powermock from source (mvn clean install -Dmaven.javadoc.skip=true) . It would be really nice if you wanted to try it out.

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [jrh...@gmail.com](https://code.google.com/u/110694536384347452794/) on November 13, 2014 07:19:13_

Got a full day today, but I'll try to get around to this within the next week, if that fits within your timeline.

**Comment by johanhaleby** [comment]
_From [jrh...@gmail.com](https://code.google.com/u/110694536384347452794/) on November 25, 2014 16:53:06_

Hmm. I tried it (I think) correctly. I installed using Java 8, update 25 and tried updating my example project, but I'm still getting a test failure.

I've pushed the POM changes to include 1.5.7-SNAPSHOT of PowerMock and the Mockito module: https://github.com/jrh3k5/powermock-mockito-0.10.x-argument-captor

**Comment by jonbarksdale** [comment]
So... I see this is closed, but I'm still getting this behavior with the latest version of powermock and mockito 1.  Was anything done for this?

**Comment by thekingnothing** [comment]
@jonbarksdale, for imported issues it hard to understand history and why it closed now. I think, it will be better if you re-created an issue with description of your case.

**Comment by jonbarksdale** [comment]
@thekingnothing I'll see if I can put together a small test case that replicates it then, and open a new ticket.
